#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one stage per section of the manual VoiceOver checklist.
#
# The rows are *parsed from the checklist at runtime*, never copied in here —
# the checklist is the source of truth and this script follows it as it changes.
# ──────────────────────────────────────────────────────────────────────────

CHECKLIST="docs/accessibility/voiceover-manual-checklist.md"
RESULTS="docs/accessibility/voiceover-results-$(date +%Y-%m-%d).md"

[[ -f "$CHECKLIST" ]] || { printf 'Run me from the repo root: %s not found\n' "$CHECKLIST" >&2; exit 1; }

# Sections and rows, straight out of the markdown tables.
_sections() { grep -E '^## [0-9]+\.' "$CHECKLIST" | sed 's/^## //'; }
_rows_for() { # $1 = section number
  awk -v want="$1" '
    /^## [0-9]+\./ { in_s = ($2 ~ "^" want "\\.") ; next }
    in_s && /^\| [0-9]+\.[0-9]+ \|/ { print }
    in_s && /^\*\*Suspected/ { print "SUSPECTED\t" $0 }
  ' "$CHECKLIST"
}
_field() { printf '%s' "$1" | awk -F' *\\| *' -v n="$2" '{print $n}'; }

TOTAL_STAGES=$(( $(_sections | wc -l | tr -d ' ') + 1 ))
DONE_COUNT=0
PASS=0; FAIL=0; SKIP=0

# A row already in the results file is a row already answered — that is what makes
# this resumable. A 55-row pass is long enough that Ctrl-C halfway through is a
# normal way to use it, not an accident.
_already_done() { [[ -f "$RESULTS" ]] && grep -qE "^\| $1 \|" "$RESULTS"; }

_init_results() {
  [[ -f "$RESULTS" ]] && return 0
  {
    printf '# VoiceOver manual pass — %s\n\n' "$(date +%Y-%m-%d)"
    printf 'Verdicts for `%s`, issue #90. Recorded with `scripts/voiceover-pass.sh`.\n\n' "$CHECKLIST"
    printf -- '- **Device:** %s\n' "${VO_DEVICE:-unrecorded}"
    printf -- '- **Build:** %s\n\n' "$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    printf -- '---\n\n'
  } > "$RESULTS"
}

_record() { # row, verdict, note
  printf '| %s | %s | %s |\n' "$1" "$2" "${3:-}" >> "$RESULTS"
}

# Written once per section, ever — not once per run. A resumed pass would otherwise
# drop a second table header into the middle of a section's rows.
_section_header() {
  grep -qF "## $1" "$RESULTS" 2>/dev/null && return 0
  printf '\n## %s\n\n| # | Verdict | Note |\n|---|---|---|\n' "$1" >> "$RESULTS"
}

# ask_verdict ROW STEP EXPECTED — the whole loop, one row at a time.
ask_verdict() {
  local row="$1" step_text="$2" expected="$3" reply note_text
  _clear
  printf '\n%s%s▸ Row %s%s   %s(%s of 55 · %s pass / %s fail / %s skipped)%s\n\n' \
    "$BOLD" "$BLUE" "$row" "$RESET" "$DIM" "$((DONE_COUNT + 1))" "$PASS" "$FAIL" "$SKIP" "$RESET"
  printf '  %sDo this:%s %s\n\n' "$BOLD" "$RESET" "$step_text"
  printf '  %sExpect:%s   %s\n\n' "$BOLD" "$RESET" "$expected"
  while true; do
    printf '  %s[p]%s pass  %s[f]%s fail  %s[s]%s skip  %s[q]%s stop and save  ' \
      "$GREEN" "$RESET" "$YELLOW" "$RESET" "$DIM" "$RESET" "$DIM" "$RESET"
    # A failed read is EOF, not a typo. Without this the prompt spins forever the
    # moment stdin closes — piping input at it, or a terminal going away mid-pass.
    if ! read -r reply; then
      printf '\n'; note "Input ended — saved to $RESULTS. Re-run to continue."
      printf '\n'; exit 0
    fi
    case "$reply" in
      p|P) PASS=$((PASS + 1));  printf '  %sNote (Enter for none):%s ' "$DIM" "$RESET"
           read -r note_text || true; _record "$row" "pass" "$note_text"; break ;;
      f|F) FAIL=$((FAIL + 1))
           # A failure with no description is a failure nobody can act on later.
           printf '  %sWhat happened? (this becomes the issue)%s ' "$BOLD" "$RESET"
           read -r note_text || true
           while [[ -z "$note_text" ]]; do
             printf '  %sA fail needs a description — what did VoiceOver do?%s ' "$YELLOW" "$RESET"
             read -r note_text || true
           done
           _record "$row" "**fail**" "$note_text"; break ;;
      s|S) SKIP=$((SKIP + 1)); printf '  %sWhy skipped (Enter for none):%s ' "$DIM" "$RESET"
           read -r note_text || true; _record "$row" "skipped" "$note_text"; break ;;
      q|Q) printf '\n'; note "Saved to $RESULTS — re-run to pick up where you left off."
           printf '\n'; exit 0 ;;
      *) printf '  %sp, f, s, or q.%s\n' "$YELLOW" "$RESET" ;;
    esac
  done
  DONE_COUNT=$((DONE_COUNT + 1))
}

banner "VoiceOver manual pass — issue #90"

# ── Stage 1: the device, before anything else ─────────────────────────────
stage "Setup: phone, VoiceOver, and the build under test"
say "This pass wants a real iPhone. VoiceOver in the simulator behaves differently"
say "for the rotor and for focus restoration — which is most of what these rows test."
printf '\n'
step "Plug the phone in, open Manga-Reader.xcodeproj, pick your device, and press Cmd-R."
step "On the phone: Settings > Accessibility > Accessibility Shortcut > VoiceOver."
note "Do the shortcut before turning VoiceOver on — triple-click the side button to"
note "toggle it. Without it, turning VoiceOver off while it fights you is unpleasant."
step "Then: Settings > Accessibility > VoiceOver > on."
printf '\n'
say "Gestures used below:"
note "  swipe right = next element      swipe left = previous"
note "  double-tap  = activate          two-finger swipe up = read from top"
note "  rotor       = two-finger twist (Actions, Headings)"
printf '\n'
ask VO_DEVICE "Which device are you testing on? (e.g. iPhone 15 Pro, iOS 18.2)"
_init_results
confirm "VoiceOver on and the app running?" || { note "Come back when it is."; exit 0; }

# ── One stage per checklist section ────────────────────────────────────────
# Both loops read on their own file descriptors, not stdin. `done < <(...)` would
# redirect stdin for the whole loop *body*, so the verdict prompt inside would eat
# checklist rows instead of the user's keypresses.
while IFS= read -r section <&3; do
  num="${section%%.*}"
  stage "$section"
  _clear
  printf '\n%s%s▸ Section %s%s\n\n' "$BOLD" "$BLUE" "$section" "$RESET"
  wrote_header=""
  while IFS= read -r line <&4; do
    if [[ "$line" == SUSPECTED* ]]; then
      printf '\n'; warn "${line#SUSPECTED	}"
      note "Some suspected rows were fixed in #103/#104/#110/#111 but never observed."
      note "If one was never actually broken, say so in the note rather than assuming."
      pause
      continue
    fi
    row=$(_field "$line" 2); step_text=$(_field "$line" 3); expected=$(_field "$line" 4)
    [[ -z "$row" ]] && continue
    if _already_done "$row"; then DONE_COUNT=$((DONE_COUNT + 1)); continue; fi
    [[ -z "$wrote_header" ]] && { _section_header "$section"; wrote_header=1; }
    ask_verdict "$row" "$step_text" "$expected"
  done 4< <(_rows_for "$num")
done 3< <(_sections)

# ── Close out ─────────────────────────────────────────────────────────────
_clear
printf '\n%s%s  ✓ Pass complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "$PASS pass · $FAIL fail · $SKIP skipped, written to $RESULTS"
printf '\n'
if (( FAIL > 0 )); then
  warn "$FAIL row(s) failed. File one issue per defect, labelled needs-triage,"
  note "milestone 'Accessibility & UI polish', each naming its row and the file:line."
  note "Group related rows into one issue where a single fix covers them."
  printf '\n'
fi
say "Close #90 when every row has a verdict — not when every defect is fixed."
printf '\n'
